# Generated by Django 3.2.5 on 2023-02-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piezas',
            name='precio',
        ),
    ]
