# Generated by Django 3.2.5 on 2023-02-12 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0002_remove_piezas_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiezasPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='public.piezas')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_piezasprecio', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_piezasprecio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Piezas Precios',
            },
        ),
    ]
