# Generated by Django 3.2.5 on 2023-02-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(default='Bodega', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bodega',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción'),
        ),
    ]
