# Generated by Django 3.2.5 on 2023-02-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_auto_20230219_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='usuario_sesion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='usuario_sesion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='usuario_sesion',
        ),
        migrations.RemoveField(
            model_name='piezas',
            name='usuario_sesion',
        ),
        migrations.RemoveField(
            model_name='piezasprecio',
            name='usuario_sesion',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='usuario_sesion',
        ),
        migrations.RemoveField(
            model_name='productospiezas',
            name='usuario_sesion',
        ),
    ]
