# Generated by Django 3.2.5 on 2023-03-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_detalleentradapiezas_entradapiezas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleentradapiezas',
            options={'verbose_name': 'Detalle Entradas Piezas'},
        ),
        migrations.RemoveField(
            model_name='piezas',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='detalleentradapiezas',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
