# Generated by Django 3.2.5 on 2023-03-08 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_auto_20230304_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezasprecio',
            name='bodega',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='public.bodega'),
            preserve_default=False,
        ),
    ]
